#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Oct 03 15:46:12 IST 2025
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim fsm_tb_behav -key {Behavioral:sim_1:Functional:fsm_tb} -tclbatch fsm_tb.tcl -log simulate.log"
xsim fsm_tb_behav -key {Behavioral:sim_1:Functional:fsm_tb} -tclbatch fsm_tb.tcl -log simulate.log

